server:
  port: 9090
  
spring:
  application:
    name: zuul
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
      
zuul:
  tguprefix: /
  routes:
    app:
      path: /**
      #This should point to your personal Tomcat server port that caliber is running on
      url: http://localhost:5252