server:
  port: 9090
  
spring:
  application:
    name: zuul
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
      
zuul:
  routes:
    security-by-service:
      path: /security/**
      serviceId: security
    dto-by-service:
      path: /dto/**
      serviceId: dto
