server:
  port: 5256
  
spring:
  application:
    name: location-service
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
security:
  basic:
    enabled: false