server:
  port: 9090
  
spring:
  application:
    name: zuul
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
      
zuul:
  routes:
    app:
      path: /**
      url: http://localhost:5252