server:
  port: 1345
  
spring:
  application:
    name: batch-service
    
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 15
    leaseExpirationDurationInSeconds: 30
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
security:
  basic:
    enabled: false
