server:
  port: 1212
  
spring:
  application:
    name: trainee-service
    
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 15
    leaseExpirationDurationInSeconds: 30
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
security:
  basic:
    enabled: false
  user:
    name: user
    password: pass